logs:
    - name: root
      level: info
      appenders:
          - type: FileLogAppender
            file: ./root.log
          - type: StdoutLogAppender
    - name: system
      level: debug
      appenders:
          - type: FileLogAppender
            file: ./system.log
          - type: StdoutLogAppender